### ISSUE TITLE
Are there any ready styles for the buttons?

### ISSUE THREAD

**Issue by samiheikki** [gluons/vue-github-buttons#1]
atm my button looks like this:
<img width="128" alt="screen shot 2017-04-09 at 16 22 42" src="https://cloud.githubusercontent.com/assets/8615573/24837617/d103e694-1d40-11e7-9831-44d851572fa8.png">

**Comment by gluons** [comment]
@samiheikki  Sorry, I forgot to add this documentation in readme. 🙇

Could you use this?
```javascript
import 'vue-github-buttons/dist/vue-github-buttons.css';
```

I'll add it in next release soon. 🔥 🚀

**Comment by samiheikki** [comment]
Thank you.

**Comment by gluons** [comment]
@samiheikki [1.0.1](https://github.com/gluons/vue-github-buttons/tree/v1.0.1) released. This documentation added.
