### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by itielshwartz** [gluons/vue-github-buttons#2]
just started a fresh project and got:

These dependencies were not found:

* vue-github-buttons in ./src/main.js
* vue-github-buttons/dist/vue-github-buttons.css in ./src/main.js

To install them, you can run: npm install --save vue-github-buttons vue-github-buttons/dist/vue-github-buttons.css

followed you instructions  fully  - any why you can help?

**Comment by gluons** [comment]
OK. Some files are missing when I publish to NPM.

**Comment by gluons** [comment]
Fixed it in [1.0.3](https://github.com/gluons/vue-github-buttons/releases/tag/v1.0.3). Please tell me back if you've used it.

❌ No need to run `npm install --save vue-github-buttons/dist/vue-github-buttons.css`.
✔️ You can just use `npm install --save vue-github-buttons`.

**Comment by gluons** [comment]
I've [used it myself](https://github.com/gluons/vue-github-buttons/tree/docs). It work fine.
Now fixed.
