### ISSUE TITLE
git.io page

### ISSUE THREAD

**Issue by diomed** [gluons/vue-github-buttons#22]
hi. 
sorry to bother you like this, but how to make git.io page to show complete link to repository, instead of random set of numbers and letters

**Comment by gluons** [comment]
You mean how to make url like my url (`https://git.io/vue-github-buttons`), right?

**Comment by diomed** [comment]
yes

**Comment by gluons** [comment]
I use [Git.io CLI](https://github.com/jgorset/git.io) but you can also follow [this blog](https://github.blog/2011-11-10-git-io-github-url-shortener/) from GitHub.

**Comment by diomed** [comment]
uhh... I'm a bit lost when it comes to command line. 
Would you please generate one for me?

for this repo: https://github.com/BulmaTemplates/bulma-templates

**Comment by gluons** [comment]
https://git.io/bulma-templates

Done.

**Comment by diomed** [comment]
Thanks man. I really appreciate it! 😃 
Kudos to you!

**Comment by gluons** [comment]
😊
