### ISSUE TITLE
Register components using pascal casing

### ISSUE THREAD

**Issue by idelsink** [gluons/vue-github-buttons#23]
Register components using pascal casing so that both `PascalCase` and `kebab-case` can be used for the components.

> When defining a component with PascalCase, you can use either case when referencing its custom element. That means both <my-component-name> and <MyComponentName> are acceptable.
> Taken from: <https://vuejs.org/v2/guide/components-registration.html#With-PascalCase>

### Example

Source: https://github.com/gluons/vue-github-buttons/blob/master/src/index.ts#L35
```ts
vue.component('GhBtnsStar', Star);
vue.component('GhBtnsFork', Fork);
vue.component('GhBtnsWatch', Watch);
vue.component('GhBtnsFollow', Follow);
```

**Comment by idelsink** [comment]
See pr: https://github.com/gluons/vue-github-buttons/pull/24

**Comment by gluons** [comment]
OK. Thank you for letting me know about it and your PR.  
Good point.
