### ISSUE TITLE
Clicking star button doesn't actually increment the star count?

### ISSUE THREAD

**Issue by soichih** [gluons/vue-github-buttons#8]
When I click a star button, it opens the github page but the stargazer counter remains 0; it's not increment it. Should it?

**Comment by gluons** [comment]
That is correct behavior. It's the same behavior as https://buttons.github.io/ and https://ghbtns.com/.

GitHub doesn't provide a link to **star** repo like **watch** and **fork**.

**Similar issue:** ntkme/github-buttons#10
